### ISSUE TITLE
[Question] How the highlighter behaves upon capture conflicts?

### ISSUE THREAD

**Issue by alexmozaidze** [RubixDev/syntastica#11]
Tree-sitter highlighter prioritizes the first capture and ignores the rest. Neovim's highlighter stacks captures and uses just the last capture highlight. What kind of behaviour does syntastica's highlighter have in that regard?

**Comment by RubixDev** [comment]
syntastica uses [syntastica-highlight](https://crates.io/crates/syntastica-highlight) for highlighting, which is forked from tree-sitter-highlight. That means its query behaviour is also like that of the tree-sitter highlighter. **However**, within the syntastica workspace I use preprocessing for the queries located in the root [`/queries`](https://github.com/RubixDev/syntastica/tree/main/queries) directory with the outputs being available as build artifacts in [action runs](https://github.com/RubixDev/syntastica/actions/runs/6300455877), although currently the last run is so old that those artifacts have expired. Part of that preprocessing is to reverse the order of some selected query files in order to get Neovim's behaviour.

The [project README](https://github.com/RubixDev/syntastica#general-side-products) explains a bit more:

> - [`syntastica-query-preprocessor`](https://crates.io/crates/syntastica-query-preprocessor) is a pre-processor for tree-sitter queries which allows usage of `; inherits <lang>` comments, conditional skipping of nodes with comments, usage of additional predicates like `lua-match?`, `contains?` and `any-of?`, Neovim's old injections syntax, and order reversing for priority flipping. The crate can be used to use queries designed for Neovim with the official [tree-sitter Rust bindings](https://crates.io/crates/tree-sitter) with minimal manual changes. Despite having `syntastica` in the name, the crate can be used externally and does not depend on any of the other `syntastica-` crates. In `syntastica` it is used in the [`codegen queries` xtask](https://github.com/RubixDev/syntastica/blob/main/xtask/src/codegen/queries.rs), because many of the queries are forked from [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), and to adjust the queries for older parser versions from [crates.io](https://crates.io).

Which queries should be reversed is defined by the `nvim-like` key in the [`languages.toml`](https://github.com/RubixDev/syntastica/blob/main/syntastica-macros/languages.toml) file.

The [documentation for `syntastica-query-preprocessor`](https://rubixdev.github.io/syntastica/syntastica_query_preprocessor/) also explains in detail what other effects the `nvim-like` flag has:

> Setting `nvim_like` to `true` mainly does the following:
>
> `#[not-]lua-match?`, `#[not-]any-of?` and `#[not-]contains?` predicates are replaced with a `#match?` or `#not-match?` predicate expressing the same constraint. Note that regular expressions cannot represent all Lua patterns, so the conversion from `lua-match` to `match` may fail and panic.
>
> Additional behavior differs for the kind of queries:
>
> - For highlight queries, the order of the queries is reversed. This is needed because Neovim prioritizes queries lower down in the file over earlier ones, whereas the official [tree-sitter Rust bindings](https://crates.io/crates/tree-sitter) do the opposite.
> - For injection queries, Neovim used to use `@<lang_name>`, `@content`, `@language`, and `@combined` captures. These will be replaced with the new (and official) syntax using `#set! injection.language "<lang_name>"`, `@injection.content`, `@injection.language`, and `#set! injection.combined` respectively.
> - For locals queries, Neovim uses `@scope`, `@reference`, and various `@definition.<kind>` captures. These will be replaced by the official `@local.scope`, `@local.reference`, and `@local.definition` captures.

That means if you want to edit syntastica's own queries, you can usually use Neovim's features (most queries say if they are forked from nvim-treesitter at the top of the file), but I know the current query and parser sets are 7 months outdated, I really need to update them all. But if you want to use your own queries as a syntastica user, you should provide them like how the tree-sitter highlighter expects them, or also use [`syntastica-query-preprocessor`](https://rubixdev.github.io/syntastica/syntastica_query_preprocessor/index.html).

I hope this answers your question.
